import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Provider } from 'jotai';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Movie App",
  description: "Generated by Movie App",
  icons: {
    icon: 'images/logo.png'
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Provider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
          {children}
          <div className="ocean">
            <div className="wave"></div>
            <div className="wave wave2"></div>
          </div>

        </body>

      </html>
    </Provider>
  );
}
